package swyftx

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"runtime"
	"io/ioutil"
)

const (
	defaultURL = "https://API.swyftx.com.au/"
)

// Client holds the connection to the swyftx API and the API key and token
// for authentication
type Client struct {
	// HTTPClient used to send HTTP requests, set to http.DefaultClient by default
	HTTPClient  *http.Client
	// BaseURL to send requests to, set to the production API server by default
	BaseURL   string
	// APIKey generated by swyftx
	APIKey    string
	// AccessToken generated by the swyftx API, used by endpoints that require
	// authorisation
	AccessToken     string
	// UserAgent sent to swyftx on each request, not required but good practice.
	// Set to "goswyftx/<OS>; Service" by default
	UserAgent string

	ctx       context.Context
}

type service struct {
	client *Client
}

// NewClientWithContext will create a new client with a specified context that can be used to
// interact with the swyftx API
func NewClientWithContext(ctx context.Context, apiKey string) (*Client, error) {

	return &Client{
		HTTPClient: http.DefaultClient,
		BaseURL: defaultURL,
		APIKey: apiKey,
		UserAgent: fmt.Sprintf("goswyftx/%s; Service", runtime.GOOS),
		ctx:    ctx,
	}, nil
}

// NewClient will create a new client that can be used to interact with swyftx
func NewClient(apiKey string) (*Client, error) {
	return NewClientWithContext(context.Background(), apiKey)
}

// NewRequest will create a new request that can be sent to the swyftx API. Body
// must be a valid JSON encodable struct.
func (c *Client) NewRequest(method, url string, body interface{}) (req *http.Request, err error) {

	var buf bytes.Buffer
	if body != nil {
		if err = json.NewEncoder(&buf).Encode(body); err != nil {
			return nil, fmt.Errorf("unable to marshal request body: %w", err)
		}
	}

	req, err = http.NewRequestWithContext(c.ctx, method, url, &buf)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", "application/json")
	if len(c.AccessToken) > 0 {
		req.Header.Add("Authorization", fmt.Sprintf("Bearer %s", c.AccessToken))
	}
	req.Header.Add("User-Agent", c.UserAgent)

	return req, nil
}

// Do a HTTP request and check for swyftx API specific errors. Unmarshal's the
// JSON response into v
func (c *Client) Do(req *http.Request, v interface{}) (resp *http.Response, err error) {

	resp, err = c.HTTPClient.Do(req)
	if err != nil {
		return nil, err
	}

	// copy the response body
	var bodyBytes []byte
	bodyBytes, err = ioutil.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("unable to read response body: %w", err)
	}

	bodyReader := bytes.NewReader(bodyBytes)

	resp.Body = ioutil.NopCloser(bodyReader)

	if resp.StatusCode >= http.StatusBadRequest {

		var errResp struct {
			Error Error `json:"error"`
		}
		if err = json.NewDecoder(bodyReader).Decode(&errResp); err != nil {
			return resp, fmt.Errorf("unable to unmarshal error from server: %w", err)
		}

		return resp, &errResp.Error
	}

	if err = json.NewDecoder(bodyReader).Decode(v); err != nil {
		return resp, fmt.Errorf("unable to unmarshal response from server: %w", err)
	}

	return resp, nil
}

// Request will send a request to the swyftx API and check the response for
// swyftx API specific errors. UnMarshals the JSON response into v
func (c *Client) Request(method, path string, body, v interface{}) error {

	req, err := c.NewRequest(method, fmt.Sprintf("%s%s", c.BaseURL, path), body)
	if err != nil {
		return fmt.Errorf("unable to create new request: %w", err)
	}

	var resp *http.Response
	resp, err = c.Do(req, v)
	if err != nil {
		return fmt.Errorf("unable to do request: %w", err)
	}

	if err = resp.Body.Close(); err != nil {
		return fmt.Errorf("unable to close response body: %w", err)
	}

	return nil
}

// Get http request to the swyftx API
func (c *Client) Get(path string, v interface{}) error {
	return c.Request(http.MethodGet, path, nil, v)
}

// Post http request to the swyftx API
func (c *Client) Post(path string, body, v interface{}) error {
	return c.Request(http.MethodPost, path, body, v)
}

// Delete http request to the swyftx API
func (c *Client) Delete(path string) error {
	return c.Request(http.MethodDelete, path, nil, nil)
}

// Version of the swyftx API
func (c *Client) Version() (string, error) {
	var version struct {
		Version string `json:"version"`
	}
	if err := c.Get("info/", &version); err != nil {
		return "", nil
	}

	return version.Version, nil
}

// WithContext will update the clients context to the one provided
func (c *Client) WithContext(ctx context.Context) *Client {

	c2 := new(Client)
	if ctx == nil {
		ctx = context.Background()
	}

	*c2 = *c
	c2.ctx = ctx
	return c2
}
